charlielee/boats-animator

app/index.html
app/main.css
app/main.js
app/variables.js

By moving the JS loading to right before the closing `</body>` tag (as is the universally recommended method), all selector loading can be initialized right then instead of inside `startup()`. :smile: 
Also reworked the frame rate input to be an `input type="number"` field instead of a `confirm` dialog, which is a much nicer UX. :)
If you have any questions, comments, or concerns on any of this, please, do not hesitate to ask! :smiley:

Improve app loading + new frame rate input

---

app/animator.html
app/css/animator.css
app/js/main.js

Having them in the DOM and constantly rendering them creates an unnecessary performance drop. By keeping them in-memory only, we speed up the UI and improve overall performance.

Internalize second video and canvas

---

app/css/animator.css
app/js/main.js

This adds more clarity for someone so they know if they are in capture or preview mode. May need tweaking.
Note: I know the branch is called `splash-screen-css`, but I made the branch before I knew you redesigned the splash screen, so I just used the branch to add this change :P

Added red border around capture window

---

app/animator.html
app/js/main.js

Fixed these while working on #83. I would have waited to submit these but they are such obvious bugs that they should have already been fixed (+ one or two improvements and one important fix that was creating bugs).
* Make the Grid Overlay button use `notifyInfo()` instead `alert()`
* Update the current frame count in status bar when taking a new frame
* Set last taken frame (if possible) in playback window when deleting a
frame
* Automatically switch to capture mode if all frames are deleted
* Update frame preview selection when undoing a frame
* Fix a really bad listeners error in `confirmSet()` (`!important`)
I plan on writing a [blog post](https://triangle717.wordpress.com/) about the last one, but for a quick tl;dr here: the event listeners were getting adding to the buttons each …

(Even more) various fixes

---

app/animator.html
app/css/animator.css
app/js/main.js

A small part of my larger work on #51. This lays the groundwork for my plans and makes the notifications look nicer.
The success and info colors still need adjusting to better match the UI colors.

Rework notifications markup and styling

---

app/css/animator.css

When the `active` class is add/removed to/from `#captureWindow`, the element shrinks/grows by 2px. This PR fixes that. :)

Fix very tiny bug with border on capture window

---

app/animator.html
app/js/main.js

Fix #104, introduced in #102. If a save directory is not set on launch, immediately prompt to set it.
Also revise related messages to have consistent wording.

Fix unset save directory on launch

---

.gitignore
app/js/main.js

This is part of #112 (and now #115). When playback occurs a red line moves along the frame reel and is displayed after the frame in the reel corresponding to the frame currently being previewed (this is easier it explain visually than in words!).

Indication on frame reel of current frame being played

---

app/animator.html
app/css/animator.css
app/js/main.js

I've fixed the long term issue #65 and took the opportunity to remove some unnecessary "layer" elements. It took me a while to realise that the reason issue #65 didn't affect `#preview` was because WebKit assigns it the property `object-fit: contain;` by default - something I haven't come across before!
I'm also happy to say to say that the dodgy aspect ratio specific `calc()` widths are now gone.
Issue #117 is also fixed in this request with a transparent border being applied to the playback window.

Fix #65 - onion skinning breaks if preview area is taller than it is wide and #117

---

app/animator.html
app/js/main.js

I've made the status bar more compact and less "wordy":
Before:
After:
I've also changed a couple of things that were bugging me:
Firstly I've renamed the variable `curFrame` to `totalFrames`. This was getting really confusing for me because `curFrame` didn't really reflect the variable's purpose (which is to provide the total number of frames captured). Also the variables `curSelectedFrame` and `curPlayFrame` were similarly named to `curFrame` but act quite differently to it since they change value relatively frequently while `curFrame` is more of a constant. In addition, the variable `statusBarCurFrame` was, despite its name, often not equal to var `curFrame`
When in capture mode the frame number in the status bar is now 0. It was previously equal to the number of frames captured (or …

Improve statusbar

---

app/package.json

This forces npm v3 be used when installing the app for development. Among other things, v3 should be used because it flat-packs the node_modules folder, meaning Windows users are less likely to hit the 255 file/folder character limit.
Note: after merging this, you'll need to update your node.js installation to >= 5.8.0 to have the specified npm version unless you update npm manually (`npm install npm -g`).

Force use of npm v3

---

app/animator.html
app/css/animator.css
app/index.html
app/js/index.js
app/js/main.js
app/js/utils.js

This removes the dev-tools and refresh buttons that were in various locations. Nw.js 0.13's SDK builds provide access to dev tools via F12 and a "reload app" option accessed via right click.

Removed dev tools and reload buttons

---

app/animator.html
app/css/animator.css
app/js/main.js

This PR fixes #141 by implementing previous, next, first and last frame buttons. In addition it moves the audio toggle from the sidebar to the playback controls area:
From the picture above you can see that this does make the playback controls area a bit cluttered. As a result, when #155 is implemented, I think it would be good if the "next" and "previous" buttons were removed and their functionality be made available purely via keyboard shortcuts.
Playback controls area without previous and next buttons:

Implement previous, next, first and last frame buttons

---

app/animator.html
app/js/main.js

Fixes #136 and fixes #158. This restores appropriate playback speeds and improves playback overall using the method I explained in #136. It also performs some optimization work previously only done in my WIP, unpublished (and now lost) camera resolutions/selection code.
Additionally contains the following fixes:
* Make `videoStop()` actually stop playback by restoring a call to `videoPause()`, broke in 75f9dafbf78164d18d40a1c20808b5d8640ef334
* Correct strange `NaN` check in FPS changing (the condition will never validate, `console.log(NaN ? true : false); // false`)

Revised playback method

---

build.js
package.json
win-install/setup.iss

This PR adds [node-archiver](https://github.com/archiverjs/node-archiver) to build.js allowing the Win32 and OSX64 builds to be compressed to zip archives and the Linux builds to tar.gz archives.
Because the version number was bumped to 0.7.1 at the wrong time and the existence of the confusing v0.7.1-alpha1 build I will release v0.7.2 after this is merged.

Compress build.js output folders

---

.gitignore
app/animator.html
app/css/animator.css
app/js/main.js

This PR removes the onion skinning toggle button. 
The centre position of the onion skinning slider is now 0% opacity while sliding it to the left or right will increase the opacity of last frame captured.
In #71 @rioforce proposes having sliding to the left offer a different function to sliding to the right. This is can be implemented after #122 is merged.

Remove onion skinning toggle button #71 

---

app/css/animator.css

The notifications would break if the message was too long. This makes them flexible so the entire message is contained.

Make notifications flexible

---

app/css/animator.css
app/js/main.js

Currently when playback occurs and the frame reel has to scroll, the right side of the current selected frame's thumbnail is cut off.
This PR provides a small fix to this.

Fix playback scroll

---

app/about.html
app/animator.html
app/index.html
app/js/utils.js
package.json

This add a live reloading function (issue #199) to utils.js for development purposes. To activate live reloading `utils.setLiveReload(true)` should be typed into the devtools console. This choice is then remembered for the remainder of the current session.
I initially wanted to do perform a check for a SDK build of NW.js and have a toggle for this feature in the GUI under a Developer menu, however I was unable to find an easy way of doing so. I still think this feature is very useful in console only form though and I'd like to see this implemented asap.

Add live reloading function to utils.js #199

---

app/about.html
app/animator.html
app/css/about.css
app/css/animator.css
app/css/common.css
app/css/index.css
app/index.html

In this PR:
* Tables used for design purposes have been replaced by Flexboxes where possible.
* Unnecessary CSS has been removed
* Move more duplicated CSS to `common.css`
* Increased usage of HTML5 Semantic elements
* `animator.html` is now fully indented with 2 spaces.

Remove unnecessary CSS and convert elements to use Flexbox

---

app/animator.html
app/css/animator.css
app/css/common.css
app/js/main.js
app/js/menubar.js
app/js/shortcuts.js
install.js
package.json

This PR implements revised confirm dialogues using the SweetAlert library rather than the previous custom solution. While the old dialogues matched the general theme of BA better, I have chosen to leave the new ones as is, because they provide a greater contrast with the background.
The new dialogues return a promise and are configurable with all of the library's features, so are much more customisable than before.

Implement revised confirm dialogues #82

---

CONTRIBUTING.md
app/js/camera-resolutions.js
app/js/camera.js
app/js/index.js
app/js/main.js
build.js
package.json

This PR moves Boats Animator from NW.js 0.26 to 0.35 (Chromium 62 to 71). #222 
Initially, when I bumped the version, loading the animator window from the launcher resulted in a blank screen, any of version of NW.js from 0.27 onwards has this issue. This has been fixed by moving `win.close()` of the launcher into a callback. I have no idea why this broke.
I have also removed `createObjectURL` from media stream elements as this is no longer possible. https://developers.google.com/web/updates/2018/10/chrome-71-deps-rems#remove_urlcreateobjecturl_from_mediastream
I can't see any other obvious issues, so this PR should be good to go!

Bump NW.js to v0.35.4

---

app/js/main.js
app/js/savedirectory.js
package-lock.json
package.json

This PR warns users that frames may be overwritten if they use a directory that has been previously used for capture. If required, a warning alert displays on startup and after the user changes directory.
BertL from Bricks In Motion details this issue further:
> One issue I did have was that at one point I forgot to switch to a new folder, and accidentally overwrote (overwrited?) images I had previously taken for an earlier session. Part of that is because you can't easily start a new project (which in my case is a new shot/take) without rebooting the program. After starting up the software again, the software doesn't load the captured frames into the project or check whether it's overwriting an already captured frame.
https://www.bricksinmotion.com/forums/post/379774/#p379774
While the …

Warn of frame overwrite

---

app/js/main.js

This PR focuses on improving the methods used in frame capture to be much more optimal. Including:
* Using blob instead of base64 (`canvas.toBlob` instead of `canvas.toDataUrl`)
* Using `Buffer.from()` instead of `Buffer()`
* I have also had to port a few of the playback fixes made in the `modules` branch as they seemed to start occurring here too.
This should hopefully improve the capture delay issues mentioned here:
https://www.bricksinmotion.com/forums/post/380380/#p380380
There is still a bit of delay in frames appearing on the frame reel (as they need to be written to disk) however anecdotally capture performance seems to be far better.
_(note this doesn't modularise frame capture, that will be coming separately later!)_

Capture improvements

---

.gitignore
build.js
install.js
package-lock.json
package.json
win-install/setup.iss

This PR changes the build process to use the https://github.com/charlielee/nwjs-packager module I have developed. `nwjs-packager` builds the app with `nw-builder` and then outputs packages of the user's choice (currently .zip, .tar.gz and Inno Setup .exe).
This brings a bunch of benefits:
* `build.js` doesn't need to contain custom code to make archives and packages
* Adding .deb/.rpm/.dmg support can be done independently of boats animator
* Moves us off the defunct nwjs-builder
* Fixes windows icon issue #221

Change build to use nwjs-packager

---

app/common/File/File.js
app/main/Take/Take.js

This implements #250. I also fixed a terrible bug with the "delete any frame" feature. After using it, to delete a frame, the next frame captured would overwrite the last frame captured. 0.9.2 will be immediately released after this.

Refactor confirm take to use Promise.all and fix delete any frame bug

---

app/js/index.js
app/ui/WindowManager/WindowManager.js

This PR implements issue #219 
(Please ignore the terrible brach name. I was supposed to write issue-219-rem.size 😂) 
Using a similar approach, the index.html page (welcome window) could be added an id property to remember its size as well. (Although I think we should leave it like that, since we wouldn't want it to occupy the entire screen after reopening - even if the user scales it to do so). Hopefully that makes sense.

Remember size and position of window 

---

app/main/ExportVideo/ExportVideo.js
app/main/Project/Project.js
app/main/SaveDirectory/SaveDirectory.js
app/main/Take/Take.js

This adds a unique id to each take generated from the current Linux epoch time. I also made frame ids 5 digits long rather than 4
This will fix issue #272 and one of the most unintuitive "features" of the app where frames will be overwritten if you don't choose a new directory each time you start the app
It's true that technically if a user were to create 2 projects in the same second, or change their PCs clock back frames could still be overwritten with this change. However this is highly unlikely and this will do until a project system is fully implemented.

Add unique id to each take

---

src/js/animator/core/ExportVideo.js
src/js/animator/projects/Take.js

Fixes #289 by adding an extra step of giving files a temporary name in the `confirmTake()` method.

Fix bugs with confirmTake

---

src/animator.html
src/css/animator.css
src/css/common.css
src/js/animator/core/Camera.js
src/js/animator/core/ExportVideo.js
src/js/animator/core/PreviewOverlay.js
src/js/animator/projects/Project.js
src/js/animator/ui/CaptureOptions.js
src/js/animator/ui/OnionSkin.js

Fixes #265.
* Allows the blank camera to always be chosen (eg to allow temporary use of the camera by another application)
* Use blank camera if device error/removal
* Switch to blank camera during video export
* Show red outline on Camera Source select if on the blank camera

Improve camera removal and error handling

---

src/common/UserPreferences.ts
src/common/timeUtils.test.ts
src/common/timeUtils.ts
src/common/utils.ts
src/renderer/components/animator/Animator/Animator.tsx
src/renderer/components/animator/StatusToolbar/StatusToolbar.tsx
src/renderer/components/animator/StatusToolbar/StatusToolbarTimestamp/StatusToolbarTimestamp.css
src/renderer/components/animator/StatusToolbar/StatusToolbarTimestamp/StatusToolbarTimestamp.tsx
src/renderer/components/animator/Timeline/TimelinePosition/TimelinePosition.tsx
src/renderer/components/modals/PreferencesModal/PreferencesModal.tsx

* The status bar current frame indicator is now a button that switches between displaying frames and seconds #419 
* Adds a setting "show timestamp in seconds on startup" to show seconds rather than frames on start up.

Option to switch status bar time between frames and seconds

---

src/renderer/components/animator/Timeline/Timeline.css
src/renderer/components/animator/Timeline/Timeline.tsx
src/renderer/components/animator/Timeline/TimelineLiveView/TimelineLiveView.css
src/renderer/components/animator/Timeline/TimelinePosition/TimelinePosition.css
src/renderer/components/animator/Timeline/TimelineTrack/TimelineTrack.css
src/renderer/components/animator/Timeline/TimelineTrack/TimelineTrack.tsx
src/renderer/components/animator/Timeline/TimelineTrackItem/TimelineTrackItem.css
src/renderer/components/animator/Timeline/TimelineTrackItem/TimelineTrackItem.tsx
src/renderer/components/animator/Timeline/TimelineTrackLabel/TimelineTrackLabel.css

* Keep timeline track labels in place when timeline scrolls. Resolves #395.
* Also when you select a frame in the timeline, the scrolling behaviour will now put some margin either side of the frame

Keep timeline track labels in place when timeline scrolls

---

src/common/FileRef.ts
src/common/project/Take.ts
src/common/project/TrackItem.ts
src/common/testConstants.ts
src/renderer/components/animator/CaptureSidebarBlock/CaptureSidebarBlock.tsx
src/renderer/components/animator/Preview/Preview.tsx
src/renderer/components/animator/Timeline/TimelineTrack/TimelineTrack.tsx
src/renderer/components/animator/Timeline/TimelineTrackItem/TimelineTrackItem.css
src/renderer/components/animator/Timeline/TimelineTrackItem/TimelineTrackItem.tsx
src/renderer/components/common/AppListener/AppListener.tsx
src/renderer/context/CaptureContext/CaptureContextProvider.tsx
src/renderer/hooks/useDeviceList.ts
src/renderer/redux/slices/captureSlice.ts
src/renderer/redux/slices/projectSlice.ts
src/renderer/redux/thunks.ts
src/renderer/services/imagingDevice/ImagingDevice.ts
src/renderer/services/imagingDevice/WebMediaDevice.ts
src/renderer/services/project/projectBuilder.test.ts
src/renderer/services/project/projectBuilder.ts
src/renderer/services/project/projectCalculator.test.ts
src/renderer/services/project/projectCalculator.ts

Refactors the capture provider to be a lot simpler and less dodgy:
* The device list is now a hook directly listening to the `devicechange` JS event listener
* Fixes #450
* Fixes #391 by adding file numbers to track items. These should be recalculated when "conform take" is reimplemented.

Refactor capture provider

---

src/common/Flavors.ts
src/common/project/Project.ts
src/common/project/Take.ts
src/common/project/TrackItem.ts
src/common/testConstants.ts
src/common/utils.ts
src/main/services/devToolsExtensions/DevToolsExtensions.ts
src/renderer/components/animator/TitleToolbar/TitleToolbar.tsx
src/renderer/components/common/App/App.tsx
src/renderer/components/common/App/useAnimatorRoutesAndProviders.tsx
src/renderer/components/modals/ExportVideoModal/ExportVideoModalOptions/ExportVideoModalOptions.tsx
src/renderer/components/modals/NewProjectModal/NewProjectModal.tsx
src/renderer/context/CaptureContext/CaptureContextProvider.tsx
src/renderer/context/PersistedDirectoriesContext/PersistedDirectoriesContextProvider.tsx
src/renderer/context/PlaybackContext/PlaybackContextProvider.tsx
src/renderer/context/ProjectFilesContext.tsx/ProjectFilesContextProvider.tsx
src/renderer/services/project/projectBuilder.test.ts
src/renderer/services/project/projectBuilder.ts
src/renderer/services/project/projectCalculator.test.ts
src/renderer/services/project/projectCalculator.ts

* Store last saved datetime for the current project and current take
* Store actual project directory name rather than version without extension
* Make default project name on submit rather than before
* Store file name rather than file path for track items
* (unrelated) fix redux/react dev tools extensions not initialising on macOS

Project file improvements

---

src/renderer/components/animator/CaptureSidebarBlock/CaptureSidebarBlock.tsx
src/renderer/components/animator/Preview/Preview.tsx
src/renderer/components/modals/CaptureSourceModal/CaptureSourceModal.tsx
src/renderer/components/ui/UiSelect/UiSelect.tsx
src/renderer/context/CaptureContext/CaptureContextProvider.tsx
src/renderer/context/ImagingDeviceContext/ImagingDeviceContext.ts
src/renderer/context/ImagingDeviceContext/ImagingDeviceContextProvider.tsx
src/renderer/services/imagingDevice/ImagingDevice.ts
src/renderer/services/imagingDevice/ImagingDeviceErrors.ts
src/renderer/services/imagingDevice/ImagingDeviceResolution.test.ts
src/renderer/services/imagingDevice/ImagingDeviceResolution.ts
src/renderer/services/imagingDevice/WebMediaDevice.ts

Reimplements change resolution and refactors the ImagingDeviceContextProvider to be way nicer. It was a bit overcomplicated before because you had to update the deviceState which triggered a useEffect in order to change device.

Implement change resolution

---

.eslintrc.json
src/common/UserPreferences.ts
src/renderer/components/modals/CaptureSourceModal/CaptureSourceModal.tsx
src/renderer/components/modals/PreferencesModal/PreferencesModal.tsx
src/renderer/context/ImagingDeviceContext/ImagingDeviceContextProvider.tsx
src/renderer/hooks/useDeviceList.ts
src/renderer/services/imagingDevice/ImagingDevice.ts
src/renderer/services/imagingDevice/TestCamera.ts

Adds a test camera to the Capture Sources when an option is enabled in settings. This will make it easier to test without always requiring to have a real camera. Also handy for testing stuff that only works on some OSs (eg camera settings).

Add test camera
