app/index.html
app/main.css

There's actually a difference between setting it in the HTML (the preferred way) VS setting it in CSS. I know this isn't all of them, but I was focusing on this area so that's all I fixed.

Set the image size in the HTML

---

app/main.js

Sans the project name, of course.
Also includes a bug fix for a really bad bug that should have rendered the app unusable (there was a semicolon where a comma should have been).

Implement #13

---

app/index.html
app/main.css
app/main.js

Fixes #19 and adds a few calls to the new system in the process. You will probably want to pull these changes locally and try them out before you merge, just to see how you like it. :wink:
I think this is the first real feature I've contributed. Everything else has been taking what already existed and improving it.
P.S. It may be time to revise the roadmap...

Implement notification system

---

app/main.js

Fixes #26. This is definitely the best way to handle the case. Also notification system comes in handy again!

Display error if attempting to take pictures w/o a set output path

---

app/animator.html
app/main.js

This is all I can do for the time being. This ports the revised file deletion code, tweaks the status bar, and lays some minor groundwork for the new capture code.

Break off changes from #22 - Part 1

---

app/animator.html
app/main.css
app/main.js

This adds blocked out (with reason!) code for individual frame deletion, a revised class name, a revised `saveFrame()`, and more minor changes.
I was talking with someone today and was able to get a lot of ideas for Boats Animator and how certain things should work (though I am sure you have some too) from both technical and brickfilmer standpoints. If  I can code it all up real soon, I may only have one or two more of these PRs. :)

Break off changes from #22 - Part 2

---

app/main.js

Fixes #39. This took a big longer because I was trying something different but couldn't get it working right at this moment.

Restore onion skinning

---

app/animator.html
app/main.js

Fixes #34. The playback code will be the next thing I dive into.

Merge play/pause buttons

---

app/index.html
app/js/feed.js
app/main.css
app/main.js

Pretty self-explanatory.
Screenshot:

Restore news feed

---

app/animator.html
app/css/animator.css
app/js/main.js

* Fixes issues 3-5 of #48 + renames selector to be more accurate
* Restores word wrap on the save path (it was lost in the redesign)
* Only create the Mac toolbar on Mac (was throwing an error on Windows)
* Minor onion skin improvements (mainly individual frame deletions and to stop attempting to load an undefined file)
* The usual small cleanup

Various fixes

---

app/animator.html
app/css/animator.css
app/js/main.js

Removing things out of the sidebar, adding them to logical places on the ui.
* The loop playback has been put beside the Play and Stop buttons.
* Frame Undo button has been restyled
* Onion skinning options have been moved below the framereel
* Framerate changer has been moved to below the framereel
Unfortunately, the dynamic positioning of the below-the-framereel items are a bit unstable, so I'll have to work on those later. Some other things like the Live View button, the frame reel, need to be styled still. I'd like to know what you think!

More fixes

---

app/animator.html
app/css/animator.css
app/js/main.js

Very easy change to fix #53. :)

Confirm changes to default save path

---

app/index.html
app/js/index.js
app/js/main.js

Since the launcher is pretty separate from the rest of the application, it seemed logical to me that its JS was separated out.

Moved functions related to index.html into a separate js file.

---

app/js/main.js
app/package.json

@le717 I think this is finally sorted now. It's amazing how much trouble such a small amount of code has caused me!

Automatically create output folder if required (2)

---

app/animator.html
app/css/animator.css
app/js/main.js

It is planned for this feature to eventually be moved to the control panel, however due to some major bugs #114 this feature has been completely removed until the take system #37 is implemented.

Removed individual frame delete buttons #83

---

app/about.html
app/animator.html
app/css/about.css
app/css/animator.css
app/index.html
app/js/about.js
app/js/main.js

This PR add `Help > About Boats Animator` to the top menu. Doing so causes the following window to open:
Additionally the copyright notice has been removed from the status bar (#77) and the dev tools link has been moved to be in its place.

About window - fixes #77

---

app/animator.html
app/index.html
app/js/index.js
app/js/main.js
app/js/utils.js

(Yes, this is all me. I have been using [Codeanywhere](https://codeanywhere.com/) this morning.)
I've noticed there are a few set of methods we reuse over and over. Thus, per DRY principles, we should move them into a common place. Thus that is what I've done. This module can and likely will be expanded.
Also included:
* Renamed `capturedFramesRaw` to just `capturedFrames`
* Fixed those menu registrations you mentioned
* Removed some `onclick` attributes (I discourage these as they break separation between markup/presentation and logic).
* Encapsulated the index JS in an [IFFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression). These help promote separation between presentation and logic.

Add new utils module + various fixes

---

CONTRIBUTING.md
README.md
app/about.html
app/animator.html
app/css/about.css
app/css/animator.css
app/css/index.css
app/index.html
app/js/about.js
app/js/index.js
app/js/main.js
app/js/utils.js
app/package.json
win-install/LICENSE.rtf
win-install/setup.iss

@le717 I'm pretty sure I managed to do this correctly.

Merged master into Nwjs-013 branch

---

app/css/index.css
app/index.html
app/js/newsfeed.js

Remember, dates are formatted per locale format, so don't freak over the American format. ;)

Fix #151 and make minor feed UI adjustments

---

app/css/animator.css
app/css/index.css

This modifies the framereel's scrollbar to make it stand out less in the interface.

Restyle frame reel scroll bar #163

---

app/about.html
app/animator.html
app/css/animator.css
app/index.html
app/js/about.js
app/js/file.js
app/js/index.js
app/js/main.js
app/js/newsfeed.js
app/js/notification.js

Fixes #51. Finally got around to implementing this. Nothing too special about it. Main issue was getting new notifications to stack nicely, but I got it worked out.
Also reindented a few more scripts/areas according to code style guidelines.

Support multiple notifications

---

app/css/animator.css
app/js/notification.js

Follow-up to https://github.com/BoatsAreRockable/Boats-Animator/pull/180#issuecomment-231628966, per your request.

Fade out notifications before removal

---

app/css/index.css
app/index.html
app/js/newsfeed.js

This fixes #170 using an adapted version of @le717's [animation](http://codepen.io/le717/pen/yYZOZR).

Add a loading animation to the newsfeed

---

app/js/main.js
app/js/notification.js

While I wait on info for #186, I figured I'd go ahead and submit this bit of cleanup to the save directory. This way, it will be easier to pin-point and fix the issue. No behavior should have changed, just the way the code works. :)

Clean up save directory code

---

app/animator.html
app/css/animator.css
app/js/main.js
app/js/notification.js

Fixes #186. Also corrects the indentation of a few small places.

Ensure the save directory exists before using it

---

app/js/file.js
app/js/main.js
app/js/savedirectory.js

This moves all the save directory code into it's own file. Trying to break up and clean up the main.js file.

Add new `savedirectory` module

---

CONTRIBUTING.md
app/js/main.js
build.js
docs/introduction/system-requirements.md
package.json

I've been playing with this. Unlike updating to 0.13, this was a easy upgrade, only needing to fix our WebRTC usage. All seems to be stable and working, but I'll let you play with it and merge it when you are happy.

Update to nw.js 0.19.2

---

app/js/main.js

Fix outline appearing around last frame on frame rate change #206

---

app/animator.html
app/js/main.js
app/js/menubar.js
app/js/shortcuts.js
app/json/default-shortcuts.json
docs/features/keyboard-shortcuts.md
install.js
package.json

This stops the bugs that were occurring with the previous shortcuts being global.
In addition:
* The shortcuts displayed in the top menu bar are now taken from the first shortcut listed for each feature in `default-shortcuts.json`.
* Menubar functionality has been refactored and moved to `menubar.js`

Switch to Mousetrap shortcut library

---

app/js/main.js
app/js/shortcuts.js

Switch to live view after playback stops

---

app/animator.html
app/css/animator.css
app/json/default-shortcuts.json
app/main/Features/Features.js
app/main/FrameReel/FrameReel.js
app/main/Project/Project.js
app/main/Shortcuts/Shortcuts.js
app/main/Take/Take.js
docs/features/keyboard-shortcuts.md

A relatively straightforward feature which I think will prove pretty useful!

Implement delete frames (other than the last one)

---

app/main/Playback/Playback.js

This PR fixed #269 
Still marking it as draft as I need to do more testing to make sure it's fixed properly. :) 
Feel free to see the changes suggested.

Fixes issue #269 - Short Play breaks with less than 5 frames

---

package-lock.json
src/animator.html
src/js/animator/projects/Project.js
src/js/animator/ui/CaptureOptions.js

Added the ability to capture multiple frames at once as described in #300. Keeping this in Draft mode until reviewing etc is complete.

Added Ability to Capture Multiple Frames at once 

---

src/renderer/components/common/Icon/Icon.css
src/renderer/components/common/Icon/Icon.tsx
src/renderer/components/common/Icon/IconName.tsx
src/renderer/components/common/PageFooterItem/PageFooterItem.css
src/renderer/components/common/SidebarBlock/SidebarBlock.css
src/renderer/components/common/Tab/Tab.tsx
src/renderer/components/common/TabGroup/TabGroup.css
src/renderer/components/common/TabGroup/TabGroup.tsx
src/renderer/pages/Animator/Animator.tsx
src/renderer/styles/_sizes.css
src/renderer/styles/theme.css

* Add tab components
* Add footer and sidebar to the animator window

Reimplement tabs

---

src/renderer/components/animator/AnimationToolbar/AnimationToolbar.css
src/renderer/components/animator/AnimationToolbar/AnimationToolbar.tsx
src/renderer/components/animator/Animator/Animator.tsx
src/renderer/components/common/Input/InputCheckbox/InputCheckbox.css
src/renderer/components/common/Input/InputCheckbox/InputCheckbox.tsx
src/renderer/components/common/Input/InputGroup/InputGroup.css
src/renderer/components/common/Input/InputGroup/InputGroup.tsx
src/renderer/components/common/Input/InputLabel/InputLabel.css
src/renderer/components/common/Input/InputLabel/InputLabel.tsx
src/renderer/components/common/Input/InputNumber/InputNumber.tsx
src/renderer/components/common/Input/InputNumberAndRange/InputNumberAndRange.tsx
src/renderer/components/common/Input/InputRange/InputRange.css
src/renderer/components/common/Input/InputRange/InputRange.tsx
src/renderer/components/common/Input/InputSelect/InputSelect.tsx
src/renderer/components/common/Input/InputSwitch/InputSwitch.css
src/renderer/components/common/Input/InputSwitch/InputSwitch.tsx
src/renderer/styles/_colors.css
src/renderer/styles/theme.css

Adds a set of form inputs for general use #307

Issue 307 form inputs

---

package-lock.json
package.json
src/main/main.ts
src/main/services/devToolsExtensions/DevToolsExtensions.ts
src/renderer/redux/app/reducer.ts
src/renderer/redux/store.ts

Implements #332 
To use the devtools install in the Redux and React DevTools extensions in Google Chrome.
Then when you start Boats Animator it will locate and load these Chrome Extensions into the Electron devtools.

Enable access to React and Redux devtools

---

src/main/services/windowUtils.ts/windowUtils.ts

Fix multiple windows on macOS window activate

---

src/renderer/components/animator/AnimationToolbar/AnimationToolbar.css
src/renderer/components/animator/AnimationToolbar/AnimationToolbar.tsx
src/renderer/components/animator/Animator/Animator.tsx
src/renderer/components/animator/CaptureButtonToolbar/CaptureButtonToolbar.css
src/renderer/components/animator/CaptureButtonToolbar/CaptureButtonToolbar.tsx
src/renderer/components/animator/Preview/Preview.css
src/renderer/components/animator/Preview/Preview.tsx
src/renderer/components/animator/StatusToolbar/StatusToolbar.tsx
src/renderer/components/common/Icon/Icon.tsx
src/renderer/components/common/IconButton/IconButton.css
src/renderer/components/common/Input/InputRange/InputRange.css
src/renderer/styles/theme.css

* Make the preview feed padded on all sides
* Make toolbars same background colour as the preview area
* Adjust short play position
* Adjust playback buttons position

Preview area UI tweaks

---

src/common/Flavors.ts
src/common/Project.ts
src/common/ipc/IpcHandler.ts
src/main/services/logger/Logger.ts
src/renderer/components/animator/AnimationToolbar/AnimationToolbar.tsx
src/renderer/components/animator/Animator/Animator.tsx
src/renderer/components/animator/CaptureButtonToolbar/CaptureButtonToolbar.tsx
src/renderer/components/animator/StatusToolbar/StatusToolbar.tsx
src/renderer/components/animator/Timeline/Timeline.tsx
src/renderer/components/animator/Timeline/TimelineLiveView/TimelineLiveView.css
src/renderer/components/animator/Timeline/TimelineLiveView/TimelineLiveView.tsx
src/renderer/components/animator/Timeline/TimelineTrack/TimelineTrack.tsx
src/renderer/components/animator/Timeline/TimelineTrackItem/TimelineTrackItem.css
src/renderer/components/animator/Timeline/TimelineTrackItem/TimelineTrackItem.tsx
src/renderer/components/animator/Timeline/TimelineTrackLabel/TimelineTrackLabel.css
src/renderer/components/modals/StartupModal/StartupModal.tsx
src/renderer/context/PlaybackContext/PlaybackContext.tsx
src/renderer/context/PlaybackContext/PlaybackContextProvider.tsx
src/renderer/hooks/usePlayback.tsx
src/renderer/hooks/useRequestAnimationFrame.tsx
src/renderer/redux/app/actions.ts
src/renderer/redux/app/reducer.ts
src/renderer/redux/app/state.ts
src/renderer/services/rLogger/rLogger.ts

Reimplement playback engine using `requestAnimationFrame`. #404 
* Playback engine powered by react context
* Play button stops playback
* Stop button stops playback
* Loop through frame number in status toolbar
* Highlight the current frame in the timeline
Note: this doesn't implement looping through the frames themselves

Reimplement playback engine

---

src/renderer/components/animator/Animator/Animator.tsx
src/renderer/components/animator/Preview/Preview.tsx
src/renderer/components/animator/Preview/PreviewFrame/PreviewFrame.css
src/renderer/components/animator/Preview/PreviewFrame/PreviewFrame.tsx

Adds frame canvas playback #404

Add frame playback

---

src/renderer/components/animator/AnimationToolbar/AnimationToolbar.tsx
src/renderer/components/animator/Timeline/TimelineLiveView/TimelineLiveView.tsx
src/renderer/context/PlaybackContext/PlaybackContext.tsx
src/renderer/context/PlaybackContext/PlaybackContextProvider.tsx

Wires up the first/previous/next/last frame buttons

---

src/renderer/components/animator/AnimationToolbar/AnimationToolbar.tsx
src/renderer/components/animator/Timeline/Timeline.tsx
src/renderer/context/PlaybackContext/PlaybackContext.tsx
src/renderer/context/PlaybackContext/PlaybackContextProvider.tsx

Reimplements pause playback #413

Pause playback

---

.github/workflows/lint-and-test.yml
.github/workflows/tsc-lint-and-test.yml
package-lock.json
package.json
src/main/services/windowUtils/windowUtils.ts
tsconfig.json

* Init GitHub workflow to run tsc, eslint and tests
* Upgrade Electron to v20 (gives us a shinier title bar on Windows! ✨)

Init GitHub workflow to run tsc, eslint and tests

---

package-lock.json
package.json
src/renderer/services/project/projectBuilder.test.ts
src/renderer/services/project/projectBuilder.ts

Fixes the app not starting and video export not working on macOS. #402

Fix macOS video export

---

src/common/utils.ts
src/renderer/components/animator/AnimationToolbar/AnimationToolbar.tsx
src/renderer/components/animator/Animator/Animator.tsx
src/renderer/components/animator/PlaybackSpeedSelect/PlaybackSpeedSelect.tsx
src/renderer/components/common/Input/InputSelect/InputSelect.css
src/renderer/components/common/Input/InputSelect/InputSelect.tsx
src/renderer/context/PlaybackContext/PlaybackContextProvider.tsx
src/renderer/redux/app/actions.ts
src/renderer/redux/project/actions.ts
src/renderer/redux/project/reducer.ts
src/renderer/redux/project/state.ts
src/renderer/styles/_sizes.css
src/renderer/styles/theme.css

Implement playback speed selection

---

src/renderer/components/modals/ExportVideoModal/ExportVideoModalOptions/ExportVideoModalOptions.tsx
src/renderer/components/modals/ProjectSettingsModal/ProjectSettingsModal.tsx
src/renderer/context/CaptureContext/CaptureContextProvider.tsx
src/renderer/context/PersistedDirectoriesContext/PersistedDirectoriesContextProvider.tsx
src/renderer/context/PersistedDirectoriesContext/PersistedDirectoriesErrors.ts
src/renderer/context/ProjectFilesContext.tsx/ProjectFilesContextProvider.tsx
src/renderer/services/fileManager/FileErrors.ts
src/renderer/services/fileManager/FileInfo.ts
src/renderer/services/fileManager/FileManager.ts
src/renderer/services/project/projectBuilder.test.ts
src/renderer/services/project/projectBuilder.ts

* error if project is inside another project directory
* fix saving to project file
* reuse FileInfoId and revoke old objectURL on file update

Improved project file handling

---

src/common/PageRoute.ts
src/common/project/Project.ts
src/common/testConstants.ts
src/common/utils.ts
src/renderer/components/animator/TitleToolbar/TitleToolbar.tsx
src/renderer/components/common/App/App.tsx
src/renderer/components/common/Icon/Icon.css
src/renderer/components/common/Icon/Icon.tsx
src/renderer/components/modals/NewProjectModal/NewProjectModal.tsx
src/renderer/components/ui/UiAlert/UiAlert.tsx
src/renderer/components/ui/UiNumberInput/UiNumberInput.tsx
src/renderer/context/CaptureContext/CaptureContextProvider.tsx
src/renderer/redux/slices/projectSlice.ts
src/renderer/services/project/projectBuilder.test.ts
src/renderer/services/project/projectBuilder.ts
src/renderer/types.ts

Refactors the project settings modal to just be a NewProjectModal. Also adds a project frame rate field, better error handling and some general tidy up related to making projects.

Refactor project settings modal

---

src/renderer/components/ui/UiModal/UiModal.tsx
src/renderer/components/ui/hooks/useDelayedClose.ts

Fix the mantine modal animations not working. We have to do a weird thing as we are calling modals from react-router

Fix modal animation not working

---

src/renderer/components/common/App/App.tsx
src/renderer/components/common/AppErrorBoundary/AppErrorBoundary.tsx
src/renderer/components/ui/UiModal/UiModal.tsx
src/renderer/context/FileManagerContext/FileErrors.ts
src/renderer/context/FileManagerContext/FileManagerContextProvider.tsx
src/renderer/context/ProjectFilesContext.tsx/ProjectFilesContextProvider.tsx

Adds an error boundary component that handles react errors, uncaught promise rejections and uncaught other errors.

Add error boundary component

---

src/renderer/components/modals/CaptureSourceModal/CaptureSourceModal.tsx
src/renderer/components/modals/CaptureSourceModal/CustomResolutionInput/CustomResolutionInput.tsx
src/renderer/components/ui/UiSelect/UiSelect.tsx

Adds a custom resolution option to the camera source modal

Implement choose custom resolution
